-- MySQL Script generated by MySQL Workbench
-- Sun Sep  8 20:10:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pi-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pi-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pi-db` ;
USE `pi-db` ;

-- -----------------------------------------------------
-- Table `pi-db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi-db`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `senha` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `cpf` INT(11) NULL,
  `email` VARCHAR(60) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi-db`.`despesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi-db`.`despesas` (
  `id_despesas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NULL,
  `data` VARCHAR(45) NULL,
  `valor` FLOAT(8) NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_despesas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi-db`.`credito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi-db`.`credito` (
  `id_credito` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NULL,
  `data` VARCHAR(45) NULL,
  `valor` FLOAT(8) NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_credito`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
